# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

output: prefixed

vars:
  REGION:   '{{ default "eu-central-1" .REGION }}'
  ACCOUNT_ID: 
    sh: aws sts get-caller-identity --query Account --output text
  REPO:     '{{.ACCOUNT_ID}}.dkr.ecr.{{.REGION}}.amazonaws.com'

tasks:
  ecr-login:
    desc: Log in to the Amazon ECR
    run: when_changed
    internal: true
    cmds:
      - echo "Logging in to Amazon ECR..."
      - cmd: >
          aws ecr get-login-password --region {{.REGION}} |
          docker login --username AWS --password-stdin {{.ACCOUNT_ID}}.dkr.ecr.{{.REGION}}.amazonaws.com
        silent: true


  build:
    desc: Build the given docker file
    run: when_changed
    interactive: true
    cmds:
      - docker build -t {{.IMAGE_NAME}}:{{.TAG}} -f {{.FILE}} {{.CONTEXT}}
    vars:
      CONTEXT: '{{default "." .CONTEXT}}'
    requires:
      vars:
        - IMAGE_NAME
        - TAG
        - FILE


  push:
    desc: Push a Docker image to the Amazon ECR
    run: when_changed
    interactive: true
    deps:
      - ecr-login
      - build
    cmds:
      - docker tag {{.IMAGE_NAME}}:{{.TAG}} {{.REPO}}/{{.IMAGE_NAME}}:{{.TAG}}
      - docker push {{.REPO}}/{{.IMAGE_NAME}}:{{.TAG}}
    requires:
      vars:
        - IMAGE_NAME
        - TAG

  docker-run-*:
    desc: Run a container with the named docker image
    run: when_changed
    deps:
      - build
    cmds:
      - docker run --rm -it {{index .MATCH 0}} {{.IMAGE_NAME}}:{{.TAG}} {{.CLI_ARGS}}
    requires:
      vars:
        - IMAGE_NAME
        - TAG
